Ms6
mi-classroom/mi-web-technologien-beiboot-ss2021-PatrickAlbus pull request #11
Opened 2021-09-02 16:33 UTC by Narua2010

Diesmal sind es ein paar mehr Änderungen als sonst.

Ich habe Großteile des Projektes refactored. Außerdem habe ich die neuen Aufgaben eingebaut. Eine Ausnahme bildet hierbei die Multilinguale Lösung in den MetaDaten. Hierbei haben wir ja bereits im Discord kommuniziert. Sollte irgendwer doch noch eine Idee haben, können wir das dort gerne abklären. Ansonsten habe ich das Problem in die Dokumentation mit aufgenommen.

Darüber hinaus habe ich einige Anpassungen an der Dokumentation vorgenommen.

Ich freue mich über euer Feedback, ggf. fällt euch ja noch etwas auf, was ich vergessen habe.

2021-09-04 10:53 UTC, JanKoll requested changes
Läuft bei mir alles super, bis auf das Verändern der Metadaten. Sobald ich da speichern drücke, bekomme ich in der Konsole die Meldung `Failed to load resource: the server responded with a status of 400 (Bad Request)` und die Änderungen sind dann nach dem Reload hinfällig.

2021-09-04 11:29 UTC, Narua2010 commented
> Läuft bei mir alles super, bis auf das Verändern der Metadaten. Sobald ich da speichern drücke, bekomme ich in der Konsole die Meldung `Failed to load resource: the server responded with a status of 400 (Bad Request)` und die Änderungen sind dann nach dem Reload hinfällig.

Danke für den Hinweis, schau ich mir später Mal an - wundert mich tatsächlich etwas weil ich dachte ich hätte das oft genug getestet :D Im Zweifel muss ich dich die Tage fragen ob du Zeit hast das wir fix zusammen bei dir Mal in der Entwicklungsumgebung schauen können :)

2021-09-07 13:37 UTC, Narua2010 commented
> Läuft bei mir alles super, bis auf das Verändern der Metadaten. Sobald ich da speichern drücke, bekomme ich in der Konsole die Meldung `Failed to load resource: the server responded with a status of 400 (Bad Request)` und die Änderungen sind dann nach dem Reload hinfällig.

Also ich konnte den Fehler anscheinend beheben - hatte vergessen abzufangen dass `null`-Felder nicht mit gespeichert werden können. Wenn also ein Feld leer geblieben ist hat das Backend einen Fehler geworfen - bei mir funktioniert es nun. Sollte der Fehler noch einmal auftreten, wäre es cool wenn du mir sagst bei welchem Artefakt du welche Werte hinschreiben wolltest.

2021-09-08 16:16 UTC, BenediktEngel requested changes
Leider läuft es bei mir auch nicht ganz wie es soll. Also Frontend sieht super aus (eignetlich genau wie in den Mockups). Aber leider kann ich auch keine Daten speichern. Kriege da auch nen 400 bad request. hab aber eigentlich den aktuellen stand gezogen. Aber der builded auch irgendwie die Container nicht wirklich neu sondern sagt cached, obwohl ich alles gelöscht habe. kann also auch nen docker problem sein.. Schau ich mir aber nochmal an. 
Und sonst ist mir noch aufgefallen, dass der Download kein Zip ist. Ich denke dann würde das ganze schneller gehen. So wartet man etwas ohne eine rückmeldung zu bekommen, deshalb hab ich den Ordner jetzt 3mal runtergeladen :D 
und noch ne kleine style Sache:
<img width="1260" alt="Bildschirmfoto 2021-09-08 um 17 58 53" src="https://user-images.githubusercontent.com/32795896/132546030-3264058a-db06-4420-b3ae-d579bb85e1ac.png">
Hier liegen die Buttons über dem Label und die haben auch nicht die gleiche Margin auf der Linken Seite wie die Textfelder, ich denke das würde besser aussehen ;)

2021-09-08 17:00 UTC, BenediktEngel commented
Rebuilden hat auch nichts gebracht, auch ohne cache. und da ist dann noch nen problem aufgetreten 🙄
<img width="1625" alt="Bildschirmfoto 2021-09-08 um 18 58 50" src="https://user-images.githubusercontent.com/32795896/132552636-d813b88b-b1de-4dbe-9341-e582f031f182.png">

2021-09-09 16:43 UTC, Narua2010 commented
@BenediktEngel  ich habe die Anpassungen am Design schonmal vorgenommen. Bezüglich den Funktionsfehlern habe ich dir bereits bei Discord geschrieben, da ich den Fehler nicht repoduziert bekomme. Wenn wir einen Termin finden, würde ich kurz schauen ob die Problematik an einem Caching Problem liegt, oder ob ich den Fehler reproduziert bekomme.

2021-09-10 09:07 UTC, BenediktEngel approved these changes
Läuft jetzt

2021-09-14 15:53 UTC, JanKoll approved these changes
Läuft 👍🏻

2021-09-16 16:05 UTC, merged