Ms4
mi-classroom/mi-web-technologien-beiboot-ss2021-PatrickAlbus pull request #8
Opened 2021-06-08 15:44 UTC by Narua2010

Ich habe den JSON-Viewer eingebaut und musste dafür die Angular Version upgraden (Frag mich wann MS das endlich mal nachholt bei dem automatisch generieren oder ob die nicht mehr mit Angular weiter arbeiten wollen)

2021-06-08 18:02 UTC, BenediktEngel commented on backend/WTBeiboot_SS21_Albus/appsettings.json
> +    "ImageJson": "imageData-1.1.json"
So müssten aber dann ja alle files den gleichen namen und somit die gleiche versionsnummer haben.

2021-06-08 18:09 UTC, BenediktEngel requested changes
Das einzige was mir aufgefallen ist, dass du den namen der JSON vorgibst und die wahrscheinlich je nach bild/gemälde unterschiedlich sind. Kannste das noch fixen? also das einfach nach .json datein gesucht wird? 
 Und der Title von deiner Anwendung ist noch Test, find ich nicht so fein. Sonst alles Prima!

2021-06-08 18:09 UTC, BenediktEngel commented on backend/WTBeiboot_SS21_Albus/appsettings.json
> +    "ImageJson": "imageData-1.1.json"
So müssten aber dann ja alle Dateien den gleichen Namen, also versionsnummer haben und ich denke die werden unabhängig gesetzt.

2021-06-08 18:09 UTC, BenediktEngel commented on frontend/src/assets/icons/info-circle-solid.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="info-circle" class="svg-inline--fa fa-info-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><
Hat da jemand die gleichen Icons wie ich genutzt? ;D

2021-06-08 18:15 UTC, Narua2010 commented on frontend/src/assets/icons/info-circle-solid.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="info-circle" class="svg-inline--fa fa-info-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><
Font-Awesome 😅

2021-06-08 18:16 UTC, Narua2010 commented on backend/WTBeiboot_SS21_Albus/appsettings.json
> +    "ImageJson": "imageData-1.1.json"
Hätte Prof. Noss nicht gesagt das der Name konfigurierbar sein soll?

2021-06-08 18:16 UTC, Narua2010 commented on backend/WTBeiboot_SS21_Albus/appsettings.json
> +    "ImageJson": "imageData-1.1.json"
Und hatte im Zuge von Projekt 2 die Daten überprüft da waren die Namen alle identisch :)

2021-06-10 14:27 UTC, JanKoll reviewed
Funktional passt alles, so weit ich das gesehen habe. Was mir durch Zufall noch aufgefallen ist, dass bei kleineren Viewports die Sitebar komische Sachen macht. Der Text und die Buttons laufen raus und das JSON Info Icon umbricht und verschiebt sich, sobald man hovert (siehe Bild: links vor hover, rechts danach).

![Untitled-1](https://user-images.githubusercontent.com/33149112/121542623-94cdda80-ca08-11eb-84c8-af2cba01fb58.jpg)

2021-06-12 10:19 UTC, BenediktEngel commented on backend/WTBeiboot_SS21_Albus/appsettings.json
> +    "ImageJson": "imageData-1.1.json"
Okay dann haben wir das wohl unterschiedlich verstanden. Passt also, bei dir ist der Name konfigurierbar, bei mir bekommt man das neuste JSON, ist halt so :D 
Kriegst nen approve

2021-06-12 10:19 UTC, BenediktEngel commented on frontend/src/assets/icons/info-circle-solid.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="info-circle" class="svg-inline--fa fa-info-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><
okay dann sehen die erstaunlich gleich aus

2021-06-12 10:20 UTC, BenediktEngel approved these changes

2021-06-15 10:36 UTC, JanKoll approved these changes

2021-06-15 10:46 UTC, merged